// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbWgTBQ6QwLcKEFbpp4xN3Cjrs_IXsd1Y',
    appId: '1:644755236366:web:5e29af611fb0d6247a7e5f',
    messagingSenderId: '644755236366',
    projectId: 'newsapp-af654',
    authDomain: 'newsapp-af654.firebaseapp.com',
    storageBucket: 'newsapp-af654.firebasestorage.app',
    measurementId: 'G-MC9JW791YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo4kRicHG-nQwgNkz_AjKA6n9ZLHx9rSw',
    appId: '1:644755236366:android:f7ec37357721409a7a7e5f',
    messagingSenderId: '644755236366',
    projectId: 'newsapp-af654',
    storageBucket: 'newsapp-af654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrH_4_CxxYjzBWmw7P4i4pebc1nq91wok',
    appId: '1:644755236366:ios:4625c340cdce862a7a7e5f',
    messagingSenderId: '644755236366',
    projectId: 'newsapp-af654',
    storageBucket: 'newsapp-af654.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrH_4_CxxYjzBWmw7P4i4pebc1nq91wok',
    appId: '1:644755236366:ios:4625c340cdce862a7a7e5f',
    messagingSenderId: '644755236366',
    projectId: 'newsapp-af654',
    storageBucket: 'newsapp-af654.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbWgTBQ6QwLcKEFbpp4xN3Cjrs_IXsd1Y',
    appId: '1:644755236366:web:1bf001eba9086dae7a7e5f',
    messagingSenderId: '644755236366',
    projectId: 'newsapp-af654',
    authDomain: 'newsapp-af654.firebaseapp.com',
    storageBucket: 'newsapp-af654.firebasestorage.app',
    measurementId: 'G-RLDECQLWCW',
  );

}